apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: api
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
      - image: ddiamond/stuff:tacos-api
        name: api
        ports:
        - containerPort: 32001
          protocol: TCP
      imagePullSecrets:
      - name: ddiamond-docker

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: apihost
  name: apihost
spec:
  ports:
    - port: 32001
      targetPort: 32001
  selector:
    name: api
