schema_version: 20180708
name: tacos-api-test
version: 0.0.49
runtime: node
entrypoint: node func.js
format: http-stream
triggers:
- name: tacos-api-test-trigger
  type: http
  source: /tacos-api-test-trigger
